language: go
sudo: enabled
go:
- 1.9.1
install: true
matrix:
  allow_failures:
  - go: dev
  fast_finish: true
notifications:
  email: false
before_script:
- GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
- go get -t github.com/golang/lint/golint
- go get -t github.com/rakyll/gotest
- go get -t honnef.co/go/tools/cmd/megacheck
- go get -t github.com/fzipp/gocyclo
- go get -t github.com/kataras/iris
- export CI=TRAVIS
script:
- test -z $(gofmt -s -l $GO_FILES)
- go test -v -race ./...
- go vet ./...
- megacheck ./...
- gocyclo -over 19 $GO_FILES
- golint -set_exit_status $(go list ./...)
deploy:
  provider: heroku
  api_key:
    secure: TNHgC4nq6JEyOprBZ3jyy9KXC7l/AjzcFR3SuS5snD83pvnqj+L1M6Aqnrc2m2KtSI3PPcNqlbzmyqELX9CQt7DTgeCbZXyguYp61YUwchMcyqi+imM/hDNqsyMOmr6x/ml08aupgUpHkMG4Jz+hRiE3vdC3CAXEISrc3EzaOCxEIDJq5uPa83Mpfev5kIZj3eRCVinKdALsdjPqQHrr8sPYRkFbV5J5fJ+FRVN3LoMwT291EKO0XN0kd+KmuYUgUiEQyRsQekuhZuaEUgYlaNbORW9gjGzt3hhThai4pcvOPnVIVr2Kqs1/vk6ibzADM/jpmWygfOo6Ct6xsBM/9tmsL8kVoDbbsExlIyP8Dy1ijWnvsupFPWJKZi/n1Sa2ra/0lTJayDOpTOpWvz20XwHnZM54XRC4Vu7L5mBhRO/8llmg+TDALT9z8n8hYrz/d+uLlHHNsGzCvQAA0SDNuXqMtcntmRSmF/Gk58+yXvnftZv0UutrLaLNVuG30j+gnaHv4LIhN4KHE7dI2pvADIA1WerA7lrhRU9fGPBPjJaaPt5KjLZZCdFwhEWGK+TS1XQhvg7kTEtcg4V4Lnsqk21d2KObxpnfXE9qWA0i20P+wH9vX182EPlMfAr8BQfB+1Z3nkm4Sfs6IKVGYnK/HXiUirEUw87FPoqfnI+bUE4=
  app: sausagerocketapi
  on:
    repo: SausageRocketDatingService/SausageRocketApi
    branch: dev
